export {MoviesSuggestionViewController as MoviesSuggestion} from './private/MoviesSugestion/MoviesSuggestions.viewController';
export {UserLibraryViewController as UserLibrary} from './private/UserLibrary/UserLibrary.viewController';
export {SignUpViewController as SignUp} from './public/SignUp/SignUp.viewController';
export {SignInViewController as SignIn} from './public/SignIn/SignIn.viewController';
export {MyAccountViewController as MyAccount} from './private/MyAccount/MyAccount.viewController';
export {MoviesViewController as Movies} from './private/Movies/Movies.viewController';
export {ListMoviesViewController as ListMovies} from './private/ListMovies/ListMovies.viewController';
export {SelectMoviesViewController as SelectMovies} from './private/SelectMovies/SelectMovies.viewController';
export {SingleMovieViewController as SingleMovie} from './private/SingleMovie/SingleMovie.viewController';
